[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "b5ce6bb110a607922d3d3e1b2e7f87079f8759d6"
libgfortran_version = "5.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "deac702883b0f452096fa75d5961b4c277cf765bc593a5a4ed646e22968697a4"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "597992fbd4bbaeaa0627ada10317b0c02ae58267"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3f981c1eb9cefd81fda680acf16178aa9918c798114197d5b580cccf93a0ae3b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "04ff8c3264133fa4325073e4ccdb4c7698f49765"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "518d44e5753007651e6d4ce54de04d802beb853f30decd7a5cd512520d4db603"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "0fd95ed34f2dee0f87282b01b4ce76dbd924a592"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "16e1c9577e0a715f336f6c325270fddce7a78bd1da2c8e7371175138372fcf6e"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "103a20704b833e69408307b3b0bdf5ad0c161af4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "10a5e7f35c0e09e3be3aa2b1117e55c9b014165f78bb4cd3e20aaf4ce2f279ce"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "96b8b258dce922aecbc58f3e4c8fd40558c44a73"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "a5d1919852bc2e75a56c36b48b20d9053206bba6c53e0447785460a461abd24e"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "c2e6e0ccb96163302f7e29004d87aea48eaa0bea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "7b26e5c34dac09e4c65a56b4c3f7dd2af6fb53950be76318302ba35851b78c14"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "62ddf96236e8e8d8d3e19a840f67958e048339a1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "083d7a67c8797b334b6e3e24e0093f76f30cef7240d3c02c1d034d56e8f68f31"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca2e917c5da0b320dbeb967df43cb88e4e912a87"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "33e2ad20cf3b959737e2c2a8bbb489170316751c30a93932377655719e70e88a"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3061abad034ce15b259fe73221f933c91615f1e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "c81919baa31e28b9cbd58ca9f2024baf77f6a6c61905eb600622908f1db95e4a"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67e8f494430fd41ee982f45d5805b595af3278cd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3e4ab6f54c848a5e6a8ccc875ba4e9d237177e855de500595e4cf44e896bd621"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eaf43766c4a9d9814e4cd55abe90afadca48d56d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "70cb97e95e678d3da324a385dd968c215818caaccd1e5d59f25ed665b96654d6"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "378e07d57f514a5dcfe7138617fde796a378007a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "ae27a19c38434f146f0c74ee500392cfb33e3a87b26f9738b9354929f110af4b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db00ace387a129961ef10d71899e81c874ce086b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "1285238c6c9a08ae6314d735ca064aa78aa5d11c84454f969cdf8195d410d6f4"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9126066dfcd8d9ba7dd05c1c479a807f9b7446d8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "53ed64b6801305c63957ea47dbc16b3f51080e12474ef8eeb00171c8767a59d9"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c9d97776dd9fbda41dd71aa5d1f6f72c90826a6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "74bd83683aebf96a479e1de8da6fbe8b92170bafd7eec6b99a53bc40cf664020"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e6565f230085f4e85ae11b598506724abe7bf1e7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8da5778e82baa34f2d1ad046180361b160740b27ea41827b2fac0b6753adf38e"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a8b0128c6a4c4cbfaa77142d3e3be0e1d4883fb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "a3741aef8edfad23cbc286e70f7195f7e39a0d94a82512ac31ffb4f1c8a69f20"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54cb2bd3c70358596eafb6da1a027d683f4b2764"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "d2faa2444250698e70856c9d2ecab4dcd5b0b70c9005662b10e3aba5cfdde1bf"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "66a612f920391c7acac26025667dc9eb23a23f86"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3374016fbb6bba75877554f99be071f7db316ff7c91675727cacbb4f1ecddb2d"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "f46c99e00c675f42ae35a8ce18d1bbfb16add9c1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4c80eee56e4fcbeb9a17b83e414a0ca0d0343bbe674682f66223250c7cea23c4"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "eb91fab645e82022ad6162de34209c0eb13c9588"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4a4132efc57c74c3c04cdd765fa168bda6c82485be03a99acc7d4d68ec7f8756"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "d7526e1b72c27e7a0b33bdda1d93a9239feb0ab3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "125ab4efaa1129c9f5898ec145a63ded26f3594c6be3cfe07d6d9335133d257d"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "b97da20d4acf7b8d0e285473735f9626abe10600"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "bffa46328c36d00be3dac5752e2e8b908192c35d805035c571c401222e8b8e55"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "a9b68af505ac5b142db9e3c7059548fa7cb844f2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "def69fb297f760854bc40bd0a15919e1360e6a1ab402ac7518146dade03753b8"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "28f61016ec6c5b2590e52e13c92cd0dcda228ef4"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "bf18dc8ee5d5bc3fb9a416534c56fd203dfa521e1d37de54b62d0fbd3de1ae7b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "a94d2bf54749a0d3d7502b1b5e649baa456fd3c3"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "29c86793ab6073dffa952b4f4386d8b87b09a68f777d2f76e88d74aff4fd11f3"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "591bf45e83b14c49dbc2cc1697da4f7bc0d9613a"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "bdd78776300eb791025c9676d97e57ae8aa332d55680f3bc16ccb3d4e99bef03"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "728c7643da50b162909ab701d639be7c41fb1e53"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "b49942cb1e5041a9956fd419ec63aa6fb50b40398805192efa0d2c860d7e69e1"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "edb7dace5adc6ddaf04d809ee504933dec90f7b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8aa8a602485af5443d177a97d1c51f99d5a7db84f8c6a14a96f922455ca087d3"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "25b4462df68e9e4d73e882970e5726d5a11a0150"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "92ce194d162dc2c1b7d4106a5818480e070645f6e41c37ac78d24c9d7f5f28cb"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "251ff70aac382d65f6e02ec893658e81b51f9f6d"
libgfortran_version = "3.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "5708e40f6bb9fbc01d71bcdfc7ac7566415ed0196af381dec645d6c3e4fa6caa"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "77e826129778ef12319ef3076940ee42b673f2b3"
libgfortran_version = "4.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "dbe676b5e014fcdf48527d8420180901424fcd28e9ff3fd90cc653160d2779f7"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "3ab98b7d18d22dcc964c790538c54e29b00bdef5"
libgfortran_version = "5.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "1c049b8074eb058c933589dbf84d6096bd0169c5462e0e528e70cb00c7ec510c"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "4f18646ce61cac0178e3b5ebd0b00b6764931df5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "e3480ef958ae9eca696d2a837e5514a4f3bd94009f6263b76ba2d02d2203a168"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "d1903253535fc00099d5fd7c82b78a1cd59bf2e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8edbe771039e7bdc60e4e1162e30fd97f191ba056f8fdcfe405a04dfc986bc3b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "f9fbaaa9cdec56696cce45f77d8507ec9a617af1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "fb164d6d5eb3d04a0a221ce056254815395665fd139b548fdaa90d6f4d00045e"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "44fefeb55e536b9dcfaa6a212560a4ae431af20d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "13da1d375ce796026b796a3b4f3dd186b428ce1cc10b6f07d912093da7d8a12d"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "90c668440a0118149458d7c857899cd93bfc7a35"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "63511b3e6f800f9443986a002c0336b420cd292d4952678ac9187f64ae511112"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "93773d717007779537c5e18430686942db8bec2a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4a6ca0f1b5258d23b539ee5dd72fcdb9760ce964947c8c9139bfa076660b42bd"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "4beb2fb9b0e51fdb10a9783ac9baea3cb0b818ec"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "d02c34c46c82f474b97e467923b03022d423dc76a89d564c6e51d8c9c3206540"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "5319849c7279aa7f81f3d3cb9d24c04014e2b466"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "9352ef1ac72bb03018e09da0f4ed46aef2b1f775d51d3be811f1caf01f9061ad"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "34fc9db95e8a80fd155eea5a71003780c88f6800"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "16609d7327e6ee200c0f73f0dfc1db6402cfd2208ccb4b955e5fc5caf75e4e2c"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "6479a4bf7ca813f55fa3a0e1e63ea66e019682dc"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "f557e22c0d7c8f1bbb5dde32e78d7df10c29cd755b5749ff94707d018e6c128c"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "3dc614f104dde6bcaec070bfc96dbcc3fb4c1777"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "521331890f21792585469719812ebc449c12bd12c5e854ffdcf274b143f979b7"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "a7f18727c4ba728ae575e7f0986b43fe98bcc3ac"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "73cbf7e4460fb20176111e1c824542d9b863c8b28a54e9e403986ca17d60cb9b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.1.1+0/xfoil_light.v0.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
