[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "354308163300d1ebf121d50c030e7be0a13ec844"
libgfortran_version = "5.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "435b6ea079906eeb568617204322e3605b89889da1294e541dd33c7871418ac8"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "5a8e8e7844b379c933fe1dc9c8f487904339a984"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "405c7acc2be031034f005b6a96d920de3d9980b16ee7d6729add4a281e158ce5"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "dfdb9d2b41883cdfbfbdd583b7a6b82fa028d1aa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8728bce4236641b4894f891210240eaf596bebc14e005ac53eb8f8f42a0873d6"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "f73578ac6ceeb7f7f3de10776f41633c8e5c05a1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "c1137795a0e532166db815cf4b058d580b03e4eabeb42e59becce2641354b6d5"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "1a1c9dfd4c9584460a3248180d683244bc367bdc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "48b54c72823d35378b42eb142e05a6b7289e2293398de1f0e269153390c71f69"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "20b3a13e400d398413c504e1c6cbbbd0cc53c954"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "2d22cb4c847b1944f61df1410898d27447fbce3de0294ab2d071078bfb2ccc41"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "4928fbb6e6e388d080355bb2e6b3249aa83991ea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8a8a2c64f95d8e2f9a4670cf73629f50d5514f5f4bd7cea37ae8e903e0575961"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a8ddf8856b28ea99d382d37ad2484523b2c0a1bd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "79a2561ce4cce9876cf15b531d3f5f18f98a6f57031329fa34b2346bbb5cf3cd"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5b9b7cd4628394a82610743a122802955aad4660"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3148536019d0aa7569af088e77a18dfa64bf2a5761b38355ce32ce94ff1580a5"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9164ad7ea3dfb23015dd20a7f0949baaeb243d94"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8a1f57a2a9a77f74c5ba27db53ba325938fed2b5eaeb56370f7b1702c42fb8ce"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "865ab48446e6162f1ba87f203d9f748bf48cad27"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "11a31c0bec0dc4c8b2cc158053df279e37a0e512f818658fa255e1086c2e792b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60a9e875d071b3db81833e6f9985d6e96f2e24bf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "9f09b5087c9f5f83379fdb008e043a97778fe51a3aa9b631c85c83cdf5e1d140"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b65376c7cb87a60c364def8aa3195a113f2397b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "78cdb8c2450611fafcc0c339bafc1ad0efba741c7a01b2d3d650239831610e95"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "795f8b86602c1f806284866b34da84bd754efa45"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "153a666b2b15a0e4374b80a539c7f501ca92cd9844bafe3ae6416f66660208f8"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d1142f287f2bcac0dba5e6ba6cebb950c20b96d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "345b664dfea6b631a058b419f8776195baa08a42d99a2d16b9fcab0677e4a8c7"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "285237b2f521690686956c5e19792107130e47f9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4347e0487f0c4ab37ac02eec13e63adf7f8643b569b99ccb312008950d8e1f11"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc44b90ced20dca0becd5169bbc4d2eb5259e530"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "0951fe936a8a3e5cf42c36c7a4e8e73977cc413da8498647c4bfe48d0add4567"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6af3a3d63a16e833c30c072a4be7f5608712c2dd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "72789cf6aba13592739cf7a8c4a3ed0b2067c7b2af77cd1b3de7b7f4418b8f75"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7034dc2f0659c6659ec0a15a81e2427f21a25667"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "ceb62d6e5f80c5417713a5eae15fb87935ee0603e57833537c93ff06e2195e2f"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "a676a5a692ab3b400ef46df055f89658401bafa1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "9087e4a70cca65b1639751744f6b789a473b91271b69f18903d7c909c6b0dac8"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "eb1903bd39c6ef6915f122c367f7cad5a0988e1d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "0badc389c224f8366b75d74fdd25109b149308e689b17978565400b64e45e01b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "9f237d36fcba6463a35bf8091b065df1db63782e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "f7a6a98bfeb7d20c23ebd10d5abc2fa06b58335e9725affcd9dabd3bc39c93df"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "8048df49a4900855e3d89025b30ea8d5140890fb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "5e566797a6855d544e80ea81d5d4fa1de6332f1e2b3a97cc7a4c192841c9944a"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "80c137ce91781930d882de03bd08f351fd779ba2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "b82e1597ae1a4eab4f3193a2f54097362d869e61a59a4be62f2fd637ad7fea6d"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "77aef758f486b0edf116b09f1019c29258c16788"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "0ddee89dab1f39ecbb09eeeeb7f2de8c1e132cbca8412ed77b36b9b51fd1b301"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "fca724d1913f26a0837fcdb31739d9661a2be7ec"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "82b20d844ba7d47d76e8c82824aff5b0c4c38e51d84880daf19c7589f181fb64"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "6d45511653410efb38f827161ed5e74cc08b0350"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "a5e604de5e5f32dff5ff2804b64843c82c485d509b2ea75401301c32a96140d4"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "09e805f1532eef68145aa96f9d9f14bd70f0eabc"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "d1dddae99c60d8dbf8733f7a7efeb4f3f1f5a5231dfe78542f230a5a407a1d4d"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "6e505f4038d4c6b4accf14517378681c0566df62"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4dcd1e1c179255790a943274eeed0233f9564cd8de6f27f53d3fc09728ba507b"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "093063c6e45c99f5a0080c82b92dd6ce16f41e8b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "a15f9d91297e70ea9e031a0edd63bac58b413f63d2f69520452dbabee031e8bb"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "e008d28f8b3e9adb491d1712913807aec280dbaa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "f9c1a346cf210e43113d4b0827147b60c99df88939ca2163de11f8a9ba87f2e5"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "7f830e12d01e35b42eb797f1df1c3f1cc2d28066"
libgfortran_version = "3.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "2e52c7f266a185e8a89f6a06771cef6134809d7153e553b2b695fb6e162744d1"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "e342a1dfc82bbf2f3264c8aa949fa074945d2119"
libgfortran_version = "4.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "7c12c16dbf99cb7b83c449ed89a9d8c0ef9a7d285fb74f9bc385c19b60b1ff37"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "dae33b898210a25a544bf689bac77a657a3d3eb8"
libgfortran_version = "5.0.0"
os = "macos"

    [[xfoil_light.download]]
    sha256 = "deffa77eeea2ea539ed1b7a0ac8bd6e8fffbcdb0667a41b41346b92d3f5d2ea2"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "fe4702dae8336a93f7974b3cb36e9729d4335a62"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4e9341dd30f4ceb1ea903a39189b0a5ff16690d997ac67e263f34c41e458f537"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "02316238934890039ef84916ad1c4deb1fa63489"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "190a4e7b65243efb52b24389df1b810ddd8ba7b6cc814fba8204cd10a853918a"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "723584c2e2fcbd8c8dc364e20cc5b99edb717477"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "506936e10976b082ec6535069a4075a483f3874bbc7959accc8a352dfdc3af4e"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "fcf248a2502cdef218f56b454e0571a8cb04655e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3de3099818c46306db2faecf50f2f106b6fcd614ee36f8800188e7c32ca0f583"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "7f90736837cddb4091bd6de1190d25556243f5e5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "cc987dfd53206b32e5c8382d19d18c7d427806ed7a619b46c60a3609faae206c"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "b79c3413beb3a87abfb529a8490adc0809fd7504"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "c7a0d5c477c278b359e1eb32a8f1e67cab36c741ad750a8dcdba0a4f64030552"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "6ad9aeda09eda2af14a914307cba3a57330d20a2"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "f41cd0e24d8fe40c6440c36801db8b307b2fc8ec14fac38269a00eed1e61fbf9"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "0fa13ef3e20d6492f1bbfd156048aa7bdb2a9f6e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "f8f7f907c2183b4a44bcd11e46bbfb246e0558fe7b27e53ecd7b14b6d061f1ce"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "7b8a41f38003a6e15a8ee926f71fe6eedf9c08a6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "49e674115d3b4e839ae8dfda1bab998e49f6b97fc50b4b201ff2aef63983bd60"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "95133ffb370eb0b68a92e07a36735a8f8d01c945"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "08829f3b57191e103756b1dee3649613057c87edc9ccc04ebd429d13da24c38c"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "73ec4f894675fd0ec41e5c4ecd383b704c25d424"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "aad378bc24dead2b2bdbaf40eb7fae2d7a612d5af164386247cd7902cbde22f8"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "1233740179b5e4c94e2f4686af97f8ad8b6a3f1a"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "8b035bdda973a6849d2b03d77d06494358d0e5cac20874866c5263f5636cb614"
    url = "https://github.com/JuliaBinaryWrappers/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+0/xfoil_light.v0.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
